92 current  2024-12-01 09:47:29  25.05beta713897.970e93b9f82e  6.6.63                          *

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -11,14 +11,17 @@ $EDITOR debbie.nix
 
 # Early return if no changes were detected (thanks @singiamtel!)
 if git diff --quiet '*.nix'; then
-    echo "No changes detected, exiting."
-    popd
-    exit 0
+  echo "No changes detected, exiting."
+  popd
+  exit 0
 fi
 
 # Autoformat your nix files
-alejandra . &>/dev/null \
-  || ( alejandra . ; echo "formatting failed!" && exit 1)
+alejandra . &>/dev/null ||
+  (
+    alejandra .
+    echo "formatting failed!" && exit 1
+  )
 
 # Shows your changes
 git diff -U0 '*.nix'
@@ -40,3 +43,4 @@ git push
 # Back to where you were
 popd
 
+notify-send -e "NixOS Rebuilt OK!" --icon=software-update-available
